<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\UrnaEletronicaFake.Shared\UrnaEletronicaFake.Shared.csproj" />
    <ProjectReference Include="..\UrnaEletronicaFake.Core\UrnaEletronicaFake.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
