<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Packages básicos -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.6" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrnaEletronicaFake.Core\UrnaEletronicaFake.Core.csproj" />
    <ProjectReference Include="..\UrnaEletronicaFake.Shared\UrnaEletronicaFake.Shared.csproj" />
    <ProjectReference Include="..\UrnaEletronicaFake.Data\UrnaEletronicaFake.Data.csproj" />
  </ItemGroup>
</Project>
